### ISSUE TITLE
[Crash on Load]  Mod causing incompatibility issue upon loading up

### ISSUE THREAD

**Issue by dreckz** [waylanderou/almost-all-the-ores#4] opened 2020-03-13 03:37 UTC
**MC: 1.15.2
Aato: 2.0.2.1**

Crash:
Crash occurs when loading up Aato.  Unsure if it is soley this mod or the compilation of mods.

Log:
[latest.log](https://github.com/waylanderou/almost-all-the-ores/files/4327731/latest.log)

Screen cap:
![image](https://user-images.githubusercontent.com/59788491/76587494-15bebf00-64b2-11ea-8d57-17b0a423988a.png)

**Comment by dreckz** [comment] 2020-03-13 03:41
Looked a bit deeper into logs and found this:
Caused by: java.lang.ClassCastException: net.minecraft.world.gen.feature.NoFeatureConfig cannot be cast to net.minecraft.world.gen.feature.DecoratedFeatureConfig
	at waylanderou.almostalltheores.OreGeneration.handleInfestedStone(OreGeneration.java:616) ~[?:2.0.2.1]
	at waylanderou.almostalltheores.OreGeneration.setup(OreGeneration.java:52) ~[?:2.0.2.1]
	at waylanderou.almostalltheores.AlmostAllTheOres$$Lambda$6263/2139197591.run(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51]

**Comment by waylanderou** [comment] 2020-03-13 17:09
Duplicate of #3 
I should not have closed it before releasing the fix... Anyway, thanks for reporting. Issue is fixed in version 2.0.2.2 (released minutes ago) as well as a few other minor problems.
Don't forget to tell me when you release your modpack so I can try it out ! ; )

**Closed as completed by waylanderou** 2020-03-13 17:09 UTC
Labels: duplicate
